### ISSUE TITLE
Desposit and Swap text goes missing

### ISSUE THREAD

**Issue by nicosey** [commerceblock/mercury-wallet#26] opened 2021-01-27 12:16 UTC
When re-sizing the text can be lost

![image](https://user-images.githubusercontent.com/7435272/105989728-6f63b400-6099-11eb-8a45-0c1d0dc936d4.png)

![image](https://user-images.githubusercontent.com/7435272/105989773-7ee2fd00-6099-11eb-8ee0-2c74767f26fa.png)

**Comment by 86667** [comment] 2021-01-27 13:11
I think this is by design, right @Vardan-Alaverdyan ?

**Comment by Vardan-Alaverdyan** [comment] 2021-02-09 05:05
The text on buttons should be expect in case of any windows size. This will be fixed shortly.

**Comment by 86667** [comment] 2021-03-08 09:16
https://github.com/commerceblock/mercury-wallet/pull/90

**Closed by 86667** 2021-03-08 09:16 UTC
